### PR TITLE
Fixes #495 Cannot delete categories

### LINKED ISSUE #495: Cannot delete categories
Attempting to delete categories results in a 500 error.

From error log:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cd.categories_name' in 'field list'' in /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php:97
Stack trace:
#0 /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php(97): PDOStatement->execute(NULL)
#1 /home/somewebsite/public_html/2point4/includes/OSC/OM/Db.php(223): OSC\OM\DbStatement->execute()
#2 /home/somewebsite/public_html/2point4/admin/includes/functions/general.php(96): OSC\OM\Db->get('categories_desc...', 'cd.categories_n...', Array)
#3 /home/somewebsite/public_html/2point4/admin/categories.php(108): tep_get_category_tree('17', '', '0', '', true)
#4 {main}
  thrown in /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php on line 97

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

File: catalog/admin/includes/functions/general.php [hunk 1]
```diff
@@ -93,7 +93,8 @@ function tep_get_category_tree($parent_id = '0', $spacing = '', $exclude = '', $
     if ( (sizeof($category_tree_array) < 1) && ($exclude != '0') ) $category_tree_array[] = array('id' => '0', 'text' => OSCOM::getDef('text_top'));
 
     if ($include_itself) {
-      $Qcategory = $OSCOM_Db->get('categories_description', 'cd.categories_name', ['cd.language_id' => $OSCOM_Language->getId(), 'cd.categories_id' => (int)$parent_id]);
+      // $Qcategory = $OSCOM_Db->get('categories_description', 'cd.categories_name', ['cd.language_id' => $OSCOM_Language->getId(), 'cd.categories_id' => (int)$parent_id]);
```
Comment (haraldpdl) [inline catalog/admin/includes/functions/general.php]: Perfect! Can this commented out line be deleted? Thanks! 🍺

Comment (scottcwilson) [inline catalog/admin/includes/functions/general.php]: Done - sorry about that.
